### ISSUE TITLE
May not be working with Mac and Linux

### ISSUE THREAD

**Issue by spoman007** [spoman007/minimal-express-starter#1]

**Comment by neha-brahmankar** [comment]
> npx: installed 13 in 29.379s
> Cloning into 'my-express-app'...
>
> Installing dependencies...
> events.js:187
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn npm.cmd ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
>     at onErrorNT (internal/child_process.js:456:16)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
>     at onErrorNT (internal/child_process.js:456:16)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
>   errno: 'ENOENT',
>   code: 'ENOENT',
>   syscall: 'spawn npm.cmd',
>   path: 'npm.cmd',
>   spawnargs: [ 'install' ]
> }

Result of running `npx minimal-express-starter my-express-app` on Mac (Mac OS X - v10.13.6)
